project:
  type: website

website:
  title: "Juan Tellez"
  site-url: "https://juanftellez.com/"
  description: "Juan F. Tellez is an assistant professor at UC Davis."
  search: false
  navbar: false

format:
  html:
    theme:
      - sandstone
      - custom.scss
    toc: false
    highlight-style: monokai



